#!/usr/bin/env python
# coding: utf-8

import sys

from PySide6.QtGui import QAction
from PySide6.QtWidgets import QApplication, QMainWindow, QMenu, QMenuBar, QStatusBar, QLabel


class Example(QMainWindow):
    def __init__(self):
        super().__init__()
        self.init_ui()
        self.setWindowTitle('QMainWidget')

    def init_ui(self):
        menubar = QMenuBar()
        self.setMenuBar(menubar)
        menu_file = menubar.addMenu('&File')
        menu_edit = menubar.addMenu('&Edit')

        action_open = QAction('&Open', self)
        action_open.setStatusTip('Open file')
        menu_file.addAction(action_open)

        statusbar = QStatusBar()
        statusbar.setSizeGripEnabled(True)
        self.setStatusBar(statusbar)

        lab = QLabel('Status')
        statusbar.addWidget(lab)


def main():
    app = QApplication(sys.argv)
    ex = Example()
    ex.show()
    sys.exit(app.exec())


if __name__ == '__main__':
    main()
